# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Labeler": "00_jupyterlabel.ipynb"}

modules = ["jupyterlabel.py"]

doc_url = "https://anishpdalal.github.io/jupyterlabel/"

git_url = "https://github.com/anishpdalal/jupyterlabel/tree/master/"

def custom_doc_links(name): return None
